{% set python_min = "3.11" %}
{% set name = "MicroMet" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/inkenbrandt/MicroMet/archive/v{{ version }}.tar.gz
  sha256: 1be92b4c8d2a3e9b907fe95d6913d49df6329767cf0be3ad6c0f35fe2a31cd7e
  patches:
    - fix-packages.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - pandas >=1.3
    - scipy >=1.7
    - matplotlib-base >=3.4
    - plotly >=5.0
    - sqlalchemy >=1.4
    - requests >=2.25
    - pyyaml >=5.4
    - pytz >=2021.1
    - statsmodels
    - scikit-learn
    - windrose
    - python-tzdata

test:
  imports:
    - micromet
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check


about:
  home: https://github.com/inkenbrandt/MicroMet
  summary: A comprehensive Python package for micrometeorological data analysis
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inkenbrandt
